# Generated by Django 5.2.9 on 2025-12-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                (
                    "comic_type",
                    models.CharField(
                        choices=[
                            ("manga", "Manga"),
                            ("manhwa", "Manhwa"),
                            ("manhua", "Manhua"),
                            ("webtoon", "Webtoon"),
                            ("comic", "Comic"),
                        ],
                        max_length=20,
                    ),
                ),
                ("release_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("hiatus", "Hiatus"),
                        ],
                        default="ongoing",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="covers/"),
                ),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                ("total_chapters", models.PositiveIntegerField(default=0)),
                ("total_volumes", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("genres", models.ManyToManyField(blank=True, to="contents.genre")),
            ],
        ),
        migrations.CreateModel(
            name="Novel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                (
                    "novel_type",
                    models.CharField(
                        choices=[
                            ("light novel", "Light Novel"),
                            ("web novel", "Web Novel"),
                            ("novel", "Novel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("release_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("hiatus", "Hiatus"),
                        ],
                        default="ongoing",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="covers/"),
                ),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                ("total_chapters", models.PositiveIntegerField(default=0)),
                ("total_volumes", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("genres", models.ManyToManyField(blank=True, to="contents.genre")),
            ],
        ),
    ]
