# Generated by Django 5.2.9 on 2026-01-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comic",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="covers/comics"),
        ),
        migrations.AlterField(
            model_name="novel",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="covers/novels"),
        ),
    ]
