# Generated by Django 5.2.9 on 2026-01-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0002_alter_comic_cover_image_alter_novel_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comic",
            name="comic_type",
            field=models.CharField(
                choices=[
                    ("manga", "Manga"),
                    ("manhwa", "Manhwa"),
                    ("manhua", "Manhua"),
                    ("comic", "Comic"),
                ],
                max_length=20,
            ),
        ),
    ]
