# Generated by Django 5.2.9 on 2026-01-06 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contents", "0001_initial"),
        ("reviews", "0002_review_unique_user_comic_review_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "comic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="contents.comic",
                    ),
                ),
                (
                    "novel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="contents.novel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite",
                "verbose_name_plural": "Favorites",
                "ordering": ["rank"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("comic__isnull", False)),
                        fields=("user", "comic"),
                        name="unique_user_comic_favorite",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("novel__isnull", False)),
                        fields=("user", "novel"),
                        name="unique_user_novel_favorite",
                    ),
                    models.UniqueConstraint(
                        fields=("user", "rank"), name="unique_favorite_rank_per_user"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="reviews.review",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Like",
                "verbose_name_plural": "Likes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["review", "created_at"],
                        name="interaction_review__10c7de_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="interaction_user_id_6f96f4_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "review"), name="unique_user_review_like"
                    )
                ],
            },
        ),
    ]
