# Generated by Django 5.2.9 on 2026-01-06 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0001_initial"),
        ("interactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="favorite",
            name="unique_favorite_rank_per_user",
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("comic__isnull", False)),
                fields=("user", "rank", "comic"),
                name="unique_comic_rank_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("novel__isnull", False)),
                fields=("user", "rank", "novel"),
                name="unique_novel_rank_per_user",
            ),
        ),
    ]
