# Generated by Django 5.2.9 on 2026-01-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0002_remove_favorite_unique_favorite_rank_per_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={"ordering": ["rank"]},
        ),
    ]
