# Generated by Django 5.2.9 on 2026-01-06 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0001_initial"),
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                condition=models.Q(("comic__isnull", False)),
                fields=("user", "comic"),
                name="unique_user_comic_review",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                condition=models.Q(("novel__isnull", False)),
                fields=("user", "novel"),
                name="unique_user_novel_review",
            ),
        ),
    ]
